### ISSUE TITLE
error when using Chrome extension

### ISSUE THREAD

**Issue by cyberfoxmeow** [benvanik/WebGL-Inspector#173]
The error is from: https://github.com/benvanik/WebGL-Inspector/blob/c5f961dba261cbd94d9b3ff3ddbaf8b7d3bf5ef9/core/extensions/chrome/contentscript.js#L75

The error information is:

```
contentscript.js:75 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
insertScript @ contentscript.js:75


contentscript.js:75 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://lbgkfoamjmhbeemjpddkjddnknfdbdae/gli.all.js'.
    at insertScript (chrome-extension://lbgkfoamjmhbeemjpddkjddnknfdbdae/contentscript.js:75:9)
    at chrome-extension://lbgkfoamjmhbeemjpddkjddnknfdbdae/contentscript.js:100:9
chrome-extension://lbgkfoamjmhbeemjpddkjddnknfdbdae/gli.all.css:1 


        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND

```

**Comment by unphased** [comment]
same here. This is a 8 year old project though and we have no reason to expect it to work.
